# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsKnox < Formula
  desc "AWS credential process helper"
  homepage "https://github.com/null93/aws-knox"
  version "1.0.4"

  on_macos do
    on_intel do
      url "https://github.com/null93/aws-knox/releases/download/1.0.4/aws-knox_1.0.4_darwin_amd64.tar.gz"
      sha256 "b18f7b74786ef6512ab26bbbef4d5138e5ab403a189499cc5a731a424d04d199"

      def install
        bin.install "knox"
      end
    end
    on_arm do
      url "https://github.com/null93/aws-knox/releases/download/1.0.4/aws-knox_1.0.4_darwin_arm64.tar.gz"
      sha256 "c2665d6da8334f1e40ec6cb3185181039e1e8239f3563dac34c4f7036dc93fa8"

      def install
        bin.install "knox"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/aws-knox/releases/download/1.0.4/aws-knox_1.0.4_linux_amd64.tar.gz"
        sha256 "6fc8f993e8239dd4017ce2ad812fbd8e8fc22f8c4e7324824db40f28fa71cbb1"

        def install
          bin.install "knox"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/aws-knox/releases/download/1.0.4/aws-knox_1.0.4_linux_arm64.tar.gz"
        sha256 "9e89317f958a6e7292b817414aa3d338636e6814677130e0f128c9c01aa270cf"

        def install
          bin.install "knox"
        end
      end
    end
  end

  test do
    system "#{bin}/knox -v"
  end
end
