# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsKnox < Formula
  desc "AWS credential process helper"
  homepage "https://github.com/null93/aws-knox"
  version "2.1.3"

  on_macos do
    on_intel do
      url "https://github.com/null93/aws-knox/releases/download/2.1.3/aws-knox_2.1.3_darwin_amd64.tar.gz"
      sha256 "219db42b3e71e24bce0b90b9d0d8f912e53cb62999d37646b18565381b566461"

      def install
        bin.install "knox"
      end
    end
    on_arm do
      url "https://github.com/null93/aws-knox/releases/download/2.1.3/aws-knox_2.1.3_darwin_arm64.tar.gz"
      sha256 "e9636ae3a73118720aae9481f5b3cc412f143892892131d83e9009dd21300628"

      def install
        bin.install "knox"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/aws-knox/releases/download/2.1.3/aws-knox_2.1.3_linux_amd64.tar.gz"
        sha256 "7ff3ee389c8892a6d2b9fdcb6b5bb0b0aafb46b429fbd4ceb568c023f355a7ec"

        def install
          bin.install "knox"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/aws-knox/releases/download/2.1.3/aws-knox_2.1.3_linux_arm64.tar.gz"
        sha256 "dd4480e6e80ee59c64be71951c970e4dbd87e71a3de993bfbd7823c435c813f9"

        def install
          bin.install "knox"
        end
      end
    end
  end

  test do
    system "#{bin}/knox -v"
  end
end
