# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirdir < Formula
  desc "CLI tool that mirrors and templates a directory structure"
  homepage "https://github.com/null93/mirdir"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/null93/mirdir/releases/download/0.0.1/mirdir_0.0.1_darwin_arm64.tar.gz"
      sha256 "3cab1643b6ee4d8059d55057b82adb3716efa5a07ac043ba232ab981e49a8740"

      def install
        bin.install "mirdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/mirdir/releases/download/0.0.1/mirdir_0.0.1_darwin_amd64.tar.gz"
      sha256 "9e79cfe965f06d07dbb088272d4ce094406a4af5da232096d2b45bdb35394b45"

      def install
        bin.install "mirdir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/null93/mirdir/releases/download/0.0.1/mirdir_0.0.1_linux_arm64.tar.gz"
      sha256 "25b61f2e5b623ba7f20a5012730d6e37f152c5fa4df4090e07e6060c3a8fffa8"

      def install
        bin.install "mirdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/mirdir/releases/download/0.0.1/mirdir_0.0.1_linux_amd64.tar.gz"
      sha256 "125248f600887e1cdebee59f4fc92efd6ee79344b32a3c9d7d6fa8a0c044f5bd"

      def install
        bin.install "mirdir"
      end
    end
  end

  test do
    system "#{bin}/mirdir -v"
  end
end
