# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhost < Formula
  desc "NGINX config structure for provisioning virtual hosts with a CLI tool"
  homepage "https://github.com/null93/vhost"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/null93/vhost/releases/download/0.0.4/vhost_0.0.4_darwin_amd64.tar.gz"
      sha256 "e04774e06c771180f1a23789b65997db29a07ce1bfa05d20342f80fd09fb92c6"

      def install
        bin.install "vhost"
      end
    end
    on_arm do
      url "https://github.com/null93/vhost/releases/download/0.0.4/vhost_0.0.4_darwin_arm64.tar.gz"
      sha256 "e04b35fa5d344a831006f0059c479d329a23a1a7addf4d5937639eb7ac63c839"

      def install
        bin.install "vhost"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/vhost/releases/download/0.0.4/vhost_0.0.4_linux_amd64.tar.gz"
        sha256 "ea7852fcc7f792a37d30bd901c453669f69a4d4f12ce9c4f192abfbc48c45a8d"

        def install
          bin.install "vhost"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/null93/vhost/releases/download/0.0.4/vhost_0.0.4_linux_arm64.tar.gz"
        sha256 "d473ba07cdd73b36b1561254f5aafbd2b7afd761657d989fbb737bf8ae8803c0"

        def install
          bin.install "vhost"
        end
      end
    end
  end

  test do
    system "#{bin}/vhost -v"
  end
end
