# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhost < Formula
  desc "NGINX config structure for provisioning virtual hosts with a CLI tool"
  homepage "https://github.com/null93/vhost"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/null93/vhost/releases/download/0.0.1/vhost_0.0.1_darwin_arm64.tar.gz"
      sha256 "819413c201db146c6c0134efb280b24c3f00a8641bf1c05d4010241f59c254bd"

      def install
        bin.install "vhost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/vhost/releases/download/0.0.1/vhost_0.0.1_darwin_amd64.tar.gz"
      sha256 "308c5052e7cdc74bad2d251f2f164a85f237c16f650d17a4d61d5a45c8c44436"

      def install
        bin.install "vhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/null93/vhost/releases/download/0.0.1/vhost_0.0.1_linux_arm64.tar.gz"
      sha256 "f607eba39160ca166426529da44cb0c5d4586561403b4013edf81d5f4c6e6484"

      def install
        bin.install "vhost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/vhost/releases/download/0.0.1/vhost_0.0.1_linux_amd64.tar.gz"
      sha256 "527392ee31d8d0e4f82f74c069ce72a61912e8e0b60ecdd04d197b1c4d034a6d"

      def install
        bin.install "vhost"
      end
    end
  end

  test do
    system "#{bin}/vhost -v"
  end
end
