# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waterfall < Formula
  desc "Cloudformation CLI tool to analyze and visualize stack events as a waterfall diagram"
  homepage "https://github.com/null93/waterfall"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/null93/waterfall/releases/download/1.0.1/waterfall_1.0.1_darwin_arm64.tar.gz"
      sha256 "b8d1a244fb4db2d0e4812ccecb53afb9baa6ecaacee56930d470b35a315adc72"

      def install
        bin.install "waterfall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/waterfall/releases/download/1.0.1/waterfall_1.0.1_darwin_amd64.tar.gz"
      sha256 "4ca951d3d17428a340eca8d815111fe904542cd7f3aeb9307956cf0666d7c054"

      def install
        bin.install "waterfall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/null93/waterfall/releases/download/1.0.1/waterfall_1.0.1_linux_arm64.tar.gz"
      sha256 "31d1fbabfd3f6c8035a4afb6c50c6c6a58e9376d7105a0608e1a7d3698af46a4"

      def install
        bin.install "waterfall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/waterfall/releases/download/1.0.1/waterfall_1.0.1_linux_amd64.tar.gz"
      sha256 "805ac71561391e040af9b53353422e471ca968e8a33627f8df3edd595cec94e9"

      def install
        bin.install "waterfall"
      end
    end
  end

  test do
    system "#{bin}/waterfall -v"
  end
end
