# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waterfall < Formula
  desc "Cloudformation CLI tool to analyze and visualize stack events as a waterfall diagram"
  homepage "https://github.com/null93/waterfall"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/null93/waterfall/releases/download/1.0.0/waterfall_1.0.0_darwin_arm64.tar.gz"
      sha256 "d45c886655418d19bbf3a49ad1a870d0f4bc1d5f0b20896840670826b2ae5906"

      def install
        bin.install "waterfall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/waterfall/releases/download/1.0.0/waterfall_1.0.0_darwin_amd64.tar.gz"
      sha256 "f0169c2ce61f5200b3752bae8cb20d29543b56144e8144b6d951ea6921c69175"

      def install
        bin.install "waterfall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/null93/waterfall/releases/download/1.0.0/waterfall_1.0.0_linux_arm64.tar.gz"
      sha256 "a11bf8c1ce32df1ed6c68640913025d7a7ed0710058dde6b6e165d6221090173"

      def install
        bin.install "waterfall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/null93/waterfall/releases/download/1.0.0/waterfall_1.0.0_linux_amd64.tar.gz"
      sha256 "b978943a1829098d6066e50b261c6127c067873a043f392f49f5b759111910c8"

      def install
        bin.install "waterfall"
      end
    end
  end

  test do
    system "#{bin}/waterfall -v"
  end
end
